name: Frontend CI/CD Pipeline

on:
  push:
    branches: [ main, develop, master, dummy ]  # 원하는 브랜치 추가
  pull_request:
    branches: [ main, develop, master, dummy ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Build React App
        env:
          CI: false
        run: |
          npm ci
          npm run build
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/kgat-frontend:${{ github.sha }} -t $ECR_REGISTRY/kgat-frontend:latest .
          docker push $ECR_REGISTRY/kgat-frontend:${{ github.sha }}
          docker push $ECR_REGISTRY/kgat-frontend:latest
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/deployment
            AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
            sed -i "s|image: .*kgat-frontend:.*|image: ${{ steps.login-ecr.outputs.registry }}/kgat-frontend:${{ github.sha }}|" frontend-deployment.yaml
            kubectl apply -f frontend-deployment.yaml
            kubectl apply -f ingress.yaml
            kubectl rollout restart deployment/kgat-frontend

      - name: Update Kubernetes manifests
        uses: actions/checkout@v3
        with:
          repository: mapzine123/kgat-k8s-manifests 
          token: ${{ secrets.un }}
          path: k8s-manifests

      - name: Update image tag in manifests
        run: |
          cd k8s-manifests
          sed -i "s|image: .*kgat-frontend:.*|image: 676206900599.dkr.ecr.ap-northeast-2.amazonaws.com/kgat-frontend:${{ github.sha }}|" kgat-frontend.yaml
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update image to ${{ github.sha }}"
          git push